### PR TITLE
finalized merge to main branch from dev

### PR DESCRIPTION
**Pull request by pmhua**
finished mvp features + stretch (scrapping)

### CODE REVIEW

**Review by kaguda — APPROVED** [review]
excited for this merge!

**Review by PLCoster — APPROVED** [review]
Full project MVP with stretch features looking good

**Review by dreille — APPROVED** [review]
So solid!

**Review by pmhua — COMMENTED** [review]
Great Teamwork!

**Review by strangesongs — APPROVED** [review]
Breathtaking work

**Pull request merged**
